### ISSUE TITLE
TableOptimization.pix - новые названия столбцов

### ISSUE THREAD

**Issue by aademid** [NIBugakov/ProtocolOfDisagreement#10]
9fafd466-8e5a-4275-a60f-33e74eb84e3b

Новые названия делаешь "Старое_2"
В данном кейсе норм, но не масштабируемо - вдруг будет третий столбец с таким же именем. 
Немного хардкодно

**Comment by aademid** [comment]
+ бесполезный шаг\загадка\сюрприз\паскахлка
eafe4a09-483e-49fa-aecd-716566c18c75

А или не бесполезный, комментик бы закинул для чего это условия

**Comment by NIBugakov** [comment]
> 9fafd466-8e5a-4275-a60f-33e74eb84e3b
> 
> Новые названия делаешь "Старое_2" В данном кейсе норм, но не масштабируемо - вдруг будет третий столбец с таким же именем. Немного хардкодно

Не правил но учту
