### ISSUE TITLE
FindingErrors.pix - подсчет разницы

### ISSUE THREAD

**Issue by aademid** [NIBugakov/ProtocolOfDisagreement#16]
Кажется некорректно сделано
b3639535-9719-4a95-8233-eca87b1adec7

Будто данная строка отрабатывает только если в дебете\кредите есть нули, вероятно стоило сделать логику отталкиваясь от bool_a, bool_b название которых кстати не впечатляет

var difference = Math.Abs((Convert.ToDecimal(row1["Дебет"]) - Convert.ToDecimal(row2["Кредит"]))+
    (Convert.ToDecimal(row2["Дебет"]) - Convert.ToDecimal(row1["Кредит"])));

**Comment by NIBugakov** [comment]
bool_a, bool_b это все Олег ,я не виновен ) p.s. виновен конечно ,я же забыл поменять

**Comment by aademid** [comment]
Обсуждено, не исправлено, оставили как есть d543d46bd5bcde129c23d5163adec65a2929a28d
