### ISSUE TITLE
main.pix - создание таблиц

### ISSUE THREAD

**Issue by aademid** [NIBugakov/ProtocolOfDisagreement#3]
dt_sampleSecond имеет такую же структуру как dt_sampleFirst
Лучше сделать dt_sampleSecond = dt_sampleFirst.Clone() - скопировать структуру таблицы, а не дублировать ее хардкодом.
При таком подходе и нескольких таблиц в разных частях кода, дорабатывать будет проблемотично

**Comment by aademid** [comment]
FindingErrors - вот тут будет явно видно
4 активности создать таблицу, они явно должны быть одинаковые, но если сейчас надо 1 столбец поменять, ты его в 4ех местах менять будешь, лень ведь...
30f2449f-8c98-41fd-8fa4-c205017a0af1

**Comment by NIBugakov** [comment]
Справедливо. Логично. Исправлено. Вчера только о принципах ссылочного типа узнал.

**Comment by aademid** [comment]
Исправлено - d543d46bd5bcde129c23d5163adec65a2929a28d
